// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMXN2OXonswo0BEFcWBrZuNjoDCEKOBU',
    appId: '1:15254736667:web:2f1cdb0ece66e06647cdbe',
    messagingSenderId: '15254736667',
    projectId: 'aries-e4f0f',
    authDomain: 'aries-e4f0f.firebaseapp.com',
    storageBucket: 'aries-e4f0f.appspot.com',
    measurementId: 'G-DPM4YT6YQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dBgPWkO67BdwjgJDNN7bb0YewUlOxHY',
    appId: '1:15254736667:android:22cdb8d9c1b47b5947cdbe',
    messagingSenderId: '15254736667',
    projectId: 'aries-e4f0f',
    storageBucket: 'aries-e4f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXULbSX7MccplLQ_yy9LCVIP4p3YQoV7w',
    appId: '1:15254736667:ios:59db0d753c76615547cdbe',
    messagingSenderId: '15254736667',
    projectId: 'aries-e4f0f',
    storageBucket: 'aries-e4f0f.appspot.com',
    iosClientId: '15254736667-8usl6181p9u3gosu06jfs119id5t4tou.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXULbSX7MccplLQ_yy9LCVIP4p3YQoV7w',
    appId: '1:15254736667:ios:59db0d753c76615547cdbe',
    messagingSenderId: '15254736667',
    projectId: 'aries-e4f0f',
    storageBucket: 'aries-e4f0f.appspot.com',
    iosClientId: '15254736667-8usl6181p9u3gosu06jfs119id5t4tou.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
